theme: jekyll-theme-leap-day
show_downloads: True
title: Generating DSMs of Varying Complexities
description: Aseel Khanfar(<a href="uum209@psu.edu">uum209@psu.edu</a>) & Fariha Azhar
header_pages:
  - another_page.md
