theme: jekyll-theme-leap-day
show_downloads: True
title: Generating DSMs of Varying Complexities
description: Aseel Khanfar(<a href="axk5993@psu.edu">axk5993@psu.edu</a>) & Fariha Azhar(<a href="fariha-azhar@live.com">fariha-azhar@live.com</a>)
header_pages:
  - another_page.md
