theme: jekyll-theme-leap-day
show_downloads: True
title: Generating DSMs of Varying Complexities
description: Aseel Khanfar(<a href="axk5993@psu.edu">axk5993@psu.edu</a>) & Fariha Azhar(<a href="fka5079@psu.edu">fka5079@psu.edu</a>)
header_pages:
  - another_page.md
